In [1]:
import pandas as pd
pd.set_option('display.precision',2)

In [2]:
df = pd.read_excel('data.xlsx',sheet_name=1)

In [3]:
df.T.head(40)

,0,1,2,3,4,5,6,7,8,9,...,10853,10854,10855,10856,10857,10858,10859,10860,10861,10862
ID,1,2,3,4,5,6,7,8,9,10,...,10854,10855,10856,10857,10858,10859,10860,10861,10862,10863
Filial,Магнитогорский,Магнитогорский,Ростовский,Казанский,Московский,Самарский,Новосибирский,Московский,Санкт - Петербургский,Белгородский,...,Московский,Краснодарский,Московский,Кемеровский,Новосибирский,Кемеровский,Ижевский,Новосибирский,Ростовский,Белгородский
Type_ts,Иностранные,Отечественные,Отечественные,Иностранные,Иностранные,Отечественные,Иностранные,Иностранные,Отечественные,Иностранные,...,Иностранные,Иностранные,Иностранные,Иностранные,Иностранные,Иностранные,Отечественные,Иностранные,Отечественные,Иностранные
passport_region,Челябинская область,Челябинская область,Ростовская область,Республика Татарстан,Москва,Самарская область,Новосибирская область,Московская область,Санкт-Петербург,Белгородская область,...,Волгоградская область,Краснодарский край,Москва,Кемеровская область,Кемеровская область,Кемеровская область,Удмуртская Республика,Белгородская область,Ростовская область,Белгородская область
VIP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Brand,TOYOTA,LADA,LADA,KIA,DATSUN,CHEVROLET,NISSAN,TOYOTA,LADA,RENAULT,...,TOYOTA,RENAULT,PORSCHE,HYUNDAI,RENAULT,HYUNDAI,LADA,KIA,LADA,KIA
Model,RAV 4,GRANTA,GRANTA,RIO,ON-DO,NIVA,QASHQAI,LAND CRUISER,LARGUS,DUSTER,...,LAND CRUISER PRADO 150,DUSTER,MACAN,SOLARIS,DUSTER,GRAND SANTA FE,GRANTA,CERATO,GRANTA,CERATO
Yr_production,2018,2016,2018,2016,2018,2016,2012,2017,2015,2017,...,2018,2015,2017,2016,2017,2018,2016,2017,2018,2018
GAP,Нет,Нет,Нет,Нет,Нет,Да,Нет,Нет,Нет,Нет,...,Нет,Нет,Нет,Нет,Нет,Нет,Нет,Да,Нет,Нет
married,Состоит в браке,Состоит в браке,Не состоит в браке,Не состоит в браке,Состоит в браке,Состоит в браке,Состоит в браке,Состоит в браке,Состоит в браке,Состоит в браке,...,Состоит в браке,Состоит в браке,Состоит в браке,Состоит в браке,Состоит в браке,Состоит в браке,Не состоит в браке,Состоит в браке,Состоит в браке,Состоит в браке
KBM,8,8,8,8,8,6,0,6,2,8,...,8,8,8,8,9,8,4,8,8,8
KBM_prol_est,6,6,6,6,6,4,0,5,0,6,...,6,6,6,6,7,6,2,6,6,6
delta_kbm,-2,-2,-2,-2,-2,-2,-100,-1,-2,-2,...,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2
deduct,Франшиза 2-ой страховой случай,Без франшизы,Без франшизы,Без франшизы,Без франшизы,Без франшизы,Без франшизы,Без франшизы,Без франшизы,Без франшизы,...,Без франшизы,Без франшизы,Без франшизы,Без франшизы,Без франшизы,Без франшизы,Без франшизы,Без франшизы,Без франшизы,Без франшизы
deduct_amount,20000+,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
product,Классика,Компакт,Классика,Компакт,Компакт,Классика,Классика,Классика,Классика,Компакт,...,Классика,Компакт,Классика,Компакт,Уверенный,Классика,Классика,Компакт,Классика,Компакт
Bank,Банк,Банк,Банк,Сетелем,Без банка,Банк,Без банка,Без банка,Без банка,Банк,...,Без банка,Без банка,Без банка,Банк,Банк,Банк,Сетелем,Банк,Банк,Сетелем
channel - map,Автосалоны,Автосалоны,Автосалоны,Автосалоны,Розница,Розница,Розница,Автосалоны,Автосалоны,Розница,...,Автосалоны,Розница,Автосалоны,Автосалоны,Автосалоны,Автосалоны,Автосалоны,Автосалоны,Автосалоны,Автосалоны
category,NB 0-1,RN,NB 0-1,RN,NB 0-1,RN,RN,RN sppg,RN,NB 0-1,...,NB 0-1,RN,NB 0-1,RN,RN,NB 0-1,RN,RN,NB 0-1,NB 0-1
kvs_type,Водители согласно перечню,Водители согласно перечню,Водители согласно перечню,Водители согласно перечню,Водители согласно перечню,Водители согласно перечню,Водители согласно перечню,Водители согласно перечню,Водители согласно перечню,Водители согласно перечню,...,Водители согласно перечню,Водители согласно перечню,Водители согласно перечню,Водители согласно перечню,Водители согласно перечню,Водители согласно перечню,Водители согласно перечню,Водители согласно перечню,Водители согласно перечню,Водители согласно перечню
Age,42,41,49,40,58,47,70,62,69,64,...,33,70,28,34,48,44,33,55,60,51
Exp,24,4,20,15,23,20,18,39,28,27,...,12,22,3,16,20,21,15,36,32,16
discount,1,1.1,0.95,1.1,1,1.1,1,1.1,1,1.1,...,0.95,1,1,0.95,1.1,1,1,1.1,1,1
Amount - gr,1400000,200000,400000,400000,400000,400000,400000,3000000,400000,600000,...,3000000,400000,2800000,600000,400000,1800000,200000,600000,400000,1000000
sex,M,M,F,M,M,M,F,M,M,M,...,M,M,F,M,M,M,M,F,M,M
premium_car,0,0,0,0,0,0,0,1,0,0,...,1,0,1,0,0,0,0,0,0,0
price_gr,55000,10000,30000,10000,10000,10000,20000,70000,15000,10000,...,70000,10000,70000,15000,30000,70000,20000,10000,30000,15000
price_prc,0.04,0.01,0.065,0.02,0.015,0.025,0.055,0.025,0.035,0.01,...,0.035,0.015,0.03,0.025,0.065,0.035,0.08,0.01,0.05,0.015
OSAGO_clnt,0,0,1,1,0,1,1,1,0,1,...,1,1,0,1,1,1,1,0,0,0
target,0,0,1,0,0,1,0,1,1,0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10863 entries, 0 to 10862
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               10863 non-null  int64
 1   Filial           10863 non-null  object
 2   Type_ts          10863 non-null  object
 3   passport_region  10863 non-null  object
 4   VIP              284 non-null    object
 5   Brand            10863 non-null  object
 6   Model            10863 non-null  object
 7   Yr_production    10863 non-null  int64
 8   GAP              10863 non-null  object
 9   married          10863 non-null  object
 10  KBM              10863 non-null  int64
 11  KBM_prol_est     10863 non-null  int64
 12  delta_kbm        10863 non-null  int64
 13  deduct           10863 non-null  object
 14  deduct_amount    10863 non-null  object
 15  product          10863 non-null  object
 16  Bank             10863 non-null  object
 17  channel - map    10863 non-null  object
 18  category         10863 non-null  object
 19  kvs_type         10863 non-null  object
 20  Age              10863 non-null  int64
 21  Exp              10863 non-null  int64
 22  discount         10863 non-null  float64
 23  Amount - gr      10863 non-null  int64
 24  sex              10863 non-null  object
 25  premium_car      10863 non-null  int64
 26  price_gr         10863 non-null  int64
 27  price_prc        10863 non-null  float64
 28  OSAGO_clnt       10863 non-null  int64
 29  target           10863 non-null  int64
dtypes: float64(2), int64(12), object(16)
memory usage: 2.5+ MB
None

In [15]:
df.describe()

,ID,Yr_production,KBM,KBM_prol_est,delta_kbm,Age,Exp,discount,Amount - gr,premium_car,price_gr,price_prc,OSAGO_clnt,target
count,10863.00,10863.00,10863.00,10863.00,10863.00,10863.00,10863.00,10863.00,1.09e+04,10863.00,10863.00,10863.00,10863.00,10863.00
mean,5432.00,2016.94,7.06,5.20,-5.07,43.68,17.24,1.00,9.78e+05,0.09,32812.30,0.03,0.59,-0.08
std,3136.02,1.55,1.92,1.74,17.27,11.25,9.60,0.05,6.78e+05,0.28,19670.54,0.02,0.49,0.72
min,1.00,2009.00,0.00,0.00,-100.00,18.00,0.00,0.90,0.00e+00,0.00,10000.00,0.00,0.00,-1.00
25%,2716.50,2016.00,6.00,5.00,-2.00,35.00,10.00,1.00,6.00e+05,0.00,15000.00,0.02,0.00,-1.00
50%,5432.00,2018.00,8.00,6.00,-2.00,42.00,16.00,1.00,8.00e+05,0.00,30000.00,0.03,1.00,0.00
75%,8147.50,2018.00,8.00,6.00,-2.00,52.00,22.00,1.00,1.20e+06,0.00,45000.00,0.04,1.00,0.00
max,10863.00,2018.00,12.00,10.00,2.00,84.00,63.00,1.10,3.00e+06,1.00,70000.00,0.10,1.00,1.00